// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBS-lBejnolnjLSyCULxxSaTDT6TMw_YTo',
    appId: '1:715746279005:web:170ff553d904a2aaaa57b4',
    messagingSenderId: '715746279005',
    projectId: 'taskysignin-bbf87',
    authDomain: 'taskysignin-bbf87.firebaseapp.com',
    storageBucket: 'taskysignin-bbf87.appspot.com',
    measurementId: 'G-G4ZQTJH73P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxZqoxgt_uVELC-cJ25aa_bZVaQeRAoDs',
    appId: '1:715746279005:android:b178e214170407a0aa57b4',
    messagingSenderId: '715746279005',
    projectId: 'taskysignin-bbf87',
    storageBucket: 'taskysignin-bbf87.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqJExhMamntmoWr3w2l2f_PNbAu6fPZAs',
    appId: '1:715746279005:ios:8e143e117ff498eaaa57b4',
    messagingSenderId: '715746279005',
    projectId: 'taskysignin-bbf87',
    storageBucket: 'taskysignin-bbf87.appspot.com',
    iosBundleId: 'com.raj.task.taskmgmt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqJExhMamntmoWr3w2l2f_PNbAu6fPZAs',
    appId: '1:715746279005:ios:8e143e117ff498eaaa57b4',
    messagingSenderId: '715746279005',
    projectId: 'taskysignin-bbf87',
    storageBucket: 'taskysignin-bbf87.appspot.com',
    iosBundleId: 'com.raj.task.taskmgmt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBS-lBejnolnjLSyCULxxSaTDT6TMw_YTo',
    appId: '1:715746279005:web:b08e7740d21cc0e3aa57b4',
    messagingSenderId: '715746279005',
    projectId: 'taskysignin-bbf87',
    authDomain: 'taskysignin-bbf87.firebaseapp.com',
    storageBucket: 'taskysignin-bbf87.appspot.com',
    measurementId: 'G-F4MNGYNG8X',
  );
}
